#!/bin/bash
echo "Waiting for CSVs to be generated by the parameter sweep..."
while [ ! -f "lambda_hsic_sweep_results.csv" ] || [ ! -f "lambda_cate_sweep_results.csv" ]; do
    sleep 10
done
echo "CSVs found! Generating plots..."
conda run -p /home/UserData/ljx/conda_envs/dlc_env python plot_parameters.py
echo "All done."
